name: terraform-test

on:
  push:
    branches:
      - plan



jobs:
  terraform:
    name: Terraform-plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform fmt
        working-directory: ./terraform
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        id: validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan -no-color -var TF_VAR_AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}" -var TF_VAR_AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}"
        continue-on-error: true

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
        